[package]
name = "create-rust-app"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
log = "0.4"
env_logger = "0.11.4"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "2.0"

[dev-dependencies]
anyhow = "1"
