[package]
name = "cli-system-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
sysinfo = "0.30.7"
rasciigraph = "0.2.0"

